[theme]
base = "dark"
primaryColor = "#FFA421"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#282828"
textColor = "#FFFFFF"
font = "sans serif"
menuItems.icon = "🔧"
menuItems.label = "Settings"
menuItems.helpUrl = "https://docs.streamlit.io/"
